name = "placeastro"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[dev]
port = 3000

[vars]
API_URL="https://placeastro.fruition-test-u7s.workers.dev"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "d952e1399f6f4523b0c6ee5bce3945cb"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
