// Generated by Wrangler by running `wrangler types --config app.wrangler.toml`

interface Env {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	API_URL: "https://placeastro-server.fruition-test-u7s.workers.dev";
	NEXTJS_ENV: string;
	NEXT_PUBLIC_API_HOST: string;
	ASSETS: Fetcher;
}
