/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvsIndexRouteImport } from './routes/tvs.index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences.index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as TvsSearchRouteImport } from './routes/tvs.search'
import { Route as TvsAiringTodayRouteImport } from './routes/tvs.airing-today'
import { Route as TvsAiringThisWeekRouteImport } from './routes/tvs.airing-this-week'
import { Route as PreferencesTvRouteImport } from './routes/preferences.tv'
import { Route as PreferencesPersonRouteImport } from './routes/preferences.person'
import { Route as PreferencesMovieRouteImport } from './routes/preferences.movie'
import { Route as PersonSearchRouteImport } from './routes/person.search'
import { Route as MoviesSearchRouteImport } from './routes/movies.search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsIndexRoute = TvsIndexRouteImport.update({
  id: '/tvs/',
  path: '/tvs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/preferences/',
  path: '/preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsSearchRoute = TvsSearchRouteImport.update({
  id: '/tvs/search',
  path: '/tvs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsAiringTodayRoute = TvsAiringTodayRouteImport.update({
  id: '/tvs/airing-today',
  path: '/tvs/airing-today',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsAiringThisWeekRoute = TvsAiringThisWeekRouteImport.update({
  id: '/tvs/airing-this-week',
  path: '/tvs/airing-this-week',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesTvRoute = PreferencesTvRouteImport.update({
  id: '/preferences/tv',
  path: '/preferences/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesPersonRoute = PreferencesPersonRouteImport.update({
  id: '/preferences/person',
  path: '/preferences/person',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesMovieRoute = PreferencesMovieRouteImport.update({
  id: '/preferences/movie',
  path: '/preferences/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonSearchRoute = PersonSearchRouteImport.update({
  id: '/person/search',
  path: '/person/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSearchRoute = MoviesSearchRouteImport.update({
  id: '/movies/search',
  path: '/movies/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/sign-up': typeof SignUpRoute
  '/movies/search': typeof MoviesSearchRoute
  '/person/search': typeof PersonSearchRoute
  '/preferences/movie': typeof PreferencesMovieRoute
  '/preferences/person': typeof PreferencesPersonRoute
  '/preferences/tv': typeof PreferencesTvRoute
  '/tvs/airing-this-week': typeof TvsAiringThisWeekRoute
  '/tvs/airing-today': typeof TvsAiringTodayRoute
  '/tvs/search': typeof TvsSearchRoute
  '/movies': typeof MoviesIndexRoute
  '/preferences': typeof PreferencesIndexRoute
  '/tvs': typeof TvsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/sign-up': typeof SignUpRoute
  '/movies/search': typeof MoviesSearchRoute
  '/person/search': typeof PersonSearchRoute
  '/preferences/movie': typeof PreferencesMovieRoute
  '/preferences/person': typeof PreferencesPersonRoute
  '/preferences/tv': typeof PreferencesTvRoute
  '/tvs/airing-this-week': typeof TvsAiringThisWeekRoute
  '/tvs/airing-today': typeof TvsAiringTodayRoute
  '/tvs/search': typeof TvsSearchRoute
  '/movies': typeof MoviesIndexRoute
  '/preferences': typeof PreferencesIndexRoute
  '/tvs': typeof TvsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/sign-up': typeof SignUpRoute
  '/movies/search': typeof MoviesSearchRoute
  '/person/search': typeof PersonSearchRoute
  '/preferences/movie': typeof PreferencesMovieRoute
  '/preferences/person': typeof PreferencesPersonRoute
  '/preferences/tv': typeof PreferencesTvRoute
  '/tvs/airing-this-week': typeof TvsAiringThisWeekRoute
  '/tvs/airing-today': typeof TvsAiringTodayRoute
  '/tvs/search': typeof TvsSearchRoute
  '/movies/': typeof MoviesIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/tvs/': typeof TvsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recommendations'
    | '/sign-up'
    | '/movies/search'
    | '/person/search'
    | '/preferences/movie'
    | '/preferences/person'
    | '/preferences/tv'
    | '/tvs/airing-this-week'
    | '/tvs/airing-today'
    | '/tvs/search'
    | '/movies'
    | '/preferences'
    | '/tvs'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recommendations'
    | '/sign-up'
    | '/movies/search'
    | '/person/search'
    | '/preferences/movie'
    | '/preferences/person'
    | '/preferences/tv'
    | '/tvs/airing-this-week'
    | '/tvs/airing-today'
    | '/tvs/search'
    | '/movies'
    | '/preferences'
    | '/tvs'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/recommendations'
    | '/sign-up'
    | '/movies/search'
    | '/person/search'
    | '/preferences/movie'
    | '/preferences/person'
    | '/preferences/tv'
    | '/tvs/airing-this-week'
    | '/tvs/airing-today'
    | '/tvs/search'
    | '/movies/'
    | '/preferences/'
    | '/tvs/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SignUpRoute: typeof SignUpRoute
  MoviesSearchRoute: typeof MoviesSearchRoute
  PersonSearchRoute: typeof PersonSearchRoute
  PreferencesMovieRoute: typeof PreferencesMovieRoute
  PreferencesPersonRoute: typeof PreferencesPersonRoute
  PreferencesTvRoute: typeof PreferencesTvRoute
  TvsAiringThisWeekRoute: typeof TvsAiringThisWeekRoute
  TvsAiringTodayRoute: typeof TvsAiringTodayRoute
  TvsSearchRoute: typeof TvsSearchRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
  TvsIndexRoute: typeof TvsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/': {
      id: '/tvs/'
      path: '/tvs'
      fullPath: '/tvs'
      preLoaderRoute: typeof TvsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/search': {
      id: '/tvs/search'
      path: '/tvs/search'
      fullPath: '/tvs/search'
      preLoaderRoute: typeof TvsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/airing-today': {
      id: '/tvs/airing-today'
      path: '/tvs/airing-today'
      fullPath: '/tvs/airing-today'
      preLoaderRoute: typeof TvsAiringTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/airing-this-week': {
      id: '/tvs/airing-this-week'
      path: '/tvs/airing-this-week'
      fullPath: '/tvs/airing-this-week'
      preLoaderRoute: typeof TvsAiringThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/tv': {
      id: '/preferences/tv'
      path: '/preferences/tv'
      fullPath: '/preferences/tv'
      preLoaderRoute: typeof PreferencesTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/person': {
      id: '/preferences/person'
      path: '/preferences/person'
      fullPath: '/preferences/person'
      preLoaderRoute: typeof PreferencesPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/movie': {
      id: '/preferences/movie'
      path: '/preferences/movie'
      fullPath: '/preferences/movie'
      preLoaderRoute: typeof PreferencesMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/search': {
      id: '/person/search'
      path: '/person/search'
      fullPath: '/person/search'
      preLoaderRoute: typeof PersonSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/search': {
      id: '/movies/search'
      path: '/movies/search'
      fullPath: '/movies/search'
      preLoaderRoute: typeof MoviesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RecommendationsRoute: RecommendationsRoute,
  SignUpRoute: SignUpRoute,
  MoviesSearchRoute: MoviesSearchRoute,
  PersonSearchRoute: PersonSearchRoute,
  PreferencesMovieRoute: PreferencesMovieRoute,
  PreferencesPersonRoute: PreferencesPersonRoute,
  PreferencesTvRoute: PreferencesTvRoute,
  TvsAiringThisWeekRoute: TvsAiringThisWeekRoute,
  TvsAiringTodayRoute: TvsAiringTodayRoute,
  TvsSearchRoute: TvsSearchRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
  TvsIndexRoute: TvsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
